// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postID"`
	ParentID  *string   `json:"parentID,omitempty"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type CommentPage struct {
	Items      []*Comment `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID               string    `json:"id"`
	Title            string    `json:"title"`
	Content          string    `json:"content"`
	CommentsDisabled bool      `json:"commentsDisabled"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
